### ISSUE TITLE
checkpointing when writing in BigQuery?

### ISSUE THREAD

**Issue by lnicalo** [samelamin/spark-bigquery#12]
I have a doubt in relation to writing on BigQuery.

Apparently there is checkpointing in place while writing data to bigquery.

However data is written twice when the spark context is stopped and resumed. It seems that the state is not saved. 

The source code is essentially as follows:

```
val spark = SparkSession.builder
    .master("local[2]")
    .appName("ParquetToBQIngestion")
    .config("spark.streaming.stopGracefullyOnShutdown","true")
    .getOrCreate()

val df = spark
    .readStream
    .option("checkpointLocation", "./data/checkpoint")
    .schema(schema)
    .parquet("<DIRECTORY_WITH_A_STREAM_OF_PARQUET_FILES>")

  val stream = df.writeStream
    .option("checkpointLocation", "./data/checkpoint")
    .option("tableReferenceSink","<TABLE>")
    .format("com.samelamin.spark.bigquery")
    .outputMode("append")
    .start()
    .awaitTermination()
```

**Comment by samelamin** [comment]
Hi @lnicalo sorry for the late reply I was away. I will have a look at this when I get a chance today. There shouldnt be duplicate writes but there might be a bug with the writeahead logs

**Comment by samelamin** [comment]
@lnicalo I just released a fix for this, should be available on databricks soon. Version 0.1.5

Please do rank the package if you find it useful 😄

**Comment by lnicalo** [comment]
Tested on my side. Thank you.
