### ISSUE TITLE
BQ Tables partitioned by time by default

### ISSUE THREAD

**Issue by lnicalo** [samelamin/spark-bigquery#15]
After uploading data to big query, tables are always partitioned by time. How do you configure it to avoid this behavior?

Thank you

**Comment by samelamin** [comment]
Hi @lnicalo you can change the signature when saving the table, see [here](https://github.com/samelamin/spark-bigquery/blob/master/src/main/scala/com/samelamin/spark/bigquery/package.scala#L154)

FYI for structured streaming, saving to a non time partitioned table is not available at the moment
