### ISSUE TITLE
Feature Request:  Spark MapType mapping to BQuery

### ISSUE THREAD

**Issue by kurtmaile** [samelamin/spark-bigquery#17]
Hi Sam,

Firstly loving the library thanks! :)  Also enjoyed both your first blog post on the building robust pipelines (second post soon hopefully :) and your commentry on spark testing too on hangouts chat with Holden.  Spark testing is for sure challenging as Im finding, Im fairly new to spark / scala so finding my feet but enjoying it.  What is the best resources / examples for spark (scala) testing youve come across?

Unfortunately Ive been ill for the last week and have lost time on my project and wont be able to submit a PR for addimg MapType conversion to BQ to do it properly  anytime soon.(as mentioned Im quite new to this and not the quickest)  If you get time to do that it would of course be very much appreciated but understand you yourself are busy.   Otherwise I'll look at it in a few months time post go-live.

Anyway wanted to update you, say thanks and keep up the good work.
Kurt

**Comment by samelamin** [comment]
You are most welcome! Thank you for the kind words and I will make sure to pass on your thanks to Holden 

Unfortunately I am not free for the next month or so but I will share it in the twitterverse to see if anyone else would like to pick it up 😉

**Comment by kurtmaile** [comment]
Cool no probs and also the kind words are deserved! :)  Enjoy your work and insight, hopefully one day not too far away I can get myself spark productive to contribute back.  In the mean time will continue to enjoy this library cheers!
