### ISSUE TITLE
How the package writes data on BigQuery?

### ISSUE THREAD

**Issue by lnicalo** [samelamin/spark-bigquery#21]
Reviewing the source code, I understand that Spark DF are written on GCS as json files, then they are loaded from GCS into BigQuery. Can you please confirm this?

I just want to confirm that I do not use Streaming Inserts into Bigquery whose price is $0.05 per GB

Thank you

**Comment by samelamin** [comment]
Yes thats correct, we do not use streaming inserts as of yet
