### ISSUE TITLE
Structured Stremaing schema updates support timeline

### ISSUE THREAD

**Issue by kurtmaile** [samelamin/spark-bigquery#24]
Hi Sam,

You mention that this is not currently supported - is there a timeline for this at all?

Our schemas will almost certainly have attributes added over time post our initial launch (e.g more order attriburtes - these would not be breaking, mostly just addative).  Without schema updates through the stream, this makes such schema evolution more difficult in terms of managing streaming jog and also the BQ table management (e.greplaying full historic streams again but with new and overwriting which feels overkill).  

Be great to hear how you manage this currently at your company? 

Cheers once again!
Kurt

p.s - Im now going away this w/e can we reschedule to next week sometime?  Cheers mate

**Comment by samelamin** [comment]
Hi Kurt,

This isnt a limitation with the connector, but with Spark itself.

A workaround is to enable schema updates then restart the stream, this will
cause any new updates to be put into BigQuery

Give it a try and let me know if you have any further issues

And we can catch up next weekend too!
