### ISSUE TITLE
Structured Streaming - Quota Limits and Trigger Interval

### ISSUE THREAD

**Issue by kurtmaile** [samelamin/spark-bigquery#27]
Hi Sam,

Just wanted some advice based on your experience with SS and BQ quota limit management.

I just noticed that the Daily limit for BigQuery Job Loads is:

'1,000 load jobs per table per day (including failures), 50,000 load jobs per project per day (including failures)'

as there 1440 minutes in a day, the Trigger interval on the streaming query needs to be >= 2 minutes this would suggest, equating to 720 incremental executions.  Does that seem right to you?  that assumes of course that data is constantly arriving, some intervals may not have data at all and thus no load job is created.

When the new watermarking feature arrives (cant wait!), I intend to use a watermark of 10 minutes anyway (for deduping) so above wont be an issue but just wanted to confirm as currently Ive no Trigger interval set so it just constantly processes once a read is done.

CSV 	2 MB (row and cell size) - seems to indicate that a given DataFrame row cant be bigger then 2MB, which is fine.  Ours biggest are about 300KB.

Anything else on this that is a gotcha I should think about?

Cheers mate!

**Comment by kurtmaile** [comment]
Hi Sam,

I think I will need to throttle Spark to BQ to keep within the 1000 limit per table per day quota. I am thinking to add below based on a databricks example:

```
.trigger(Trigger.ProcessingTime("5 minutes"))
```
to the streamingQuery - how have you handled this with your SS deployments?  Havent tried this just yet assume its supported by the library?

Guess another reason to look at streaming inserts so such a quota concern goes away - on that thanks for sharing your details, will get an email across to you soon.

Kurt

**Comment by samelamin** [comment]
Hi @kurtmaile,

We had windows of around 10 minutes and actually never hit the limit. 

But I see 5 mins as a good limit to have. You are right, Streaming Inserts will deal with this issue but in my experience the majority of people are not streaming into BQ, rather they load batch data and end up loading in to bq less than 10 times a day
