### ISSUE TITLE
ISSUE: bq_load_timestamp corrupted

### ISSUE THREAD

**Issue by kurtmaile** [samelamin/spark-bigquery#30]
Hi Sam,

Description:

Latest release 0.18 which fixed event time watermarking may have corrupted the BQ load timestamp.  

The error below is returned by BQ indicating an invalid timestamp in bq_load_timestamp (note: the streaming queries that populate this DO NOT use watermarking BTW).  

I now need to add EXCEPT(bq_load_timestamp) on my queries to stop them erroring (will need to patch these in the future).  Refer below:

For some tests on streams that DO use the new watermarking feature, the timestmap on the sink tables is the beginning of epoc rather then the clock time. 

![image-1](https://user-images.githubusercontent.com/20066181/28246920-f34fc586-6a1d-11e7-9eba-63669d190170.png)

Let me know if you need anymore info
Kurt

**Comment by samelamin** [comment]
@kurtmaile should be all good now on v 0.1.9

**Comment by kurtmaile** [comment]
Thanks heaps - I tried testing patching the old BQ timestamps and go this error - seems I cant do update statements on partiton tables yet? Ekk.....

![image](https://user-images.githubusercontent.com/20066181/28259548-c0a1ef04-6ace-11e7-81e7-8fabc1a3180f.png)
